"""============================================================
Mr 6 — Illustrator
Generates gpt-image-1 artwork for existing problems that still
use SVG/placeholder art, and updates each problem to point at
its new PNG. The original SVGs stay on disk as fallbacks.

Usage:
    python generator/illustrate.py              # illustrate everything without a PNG
    python generator/illustrate.py --only duplicatus-of-the-deep
    python generator/illustrate.py --force      # regenerate PNGs too
    python generator/illustrate.py --quality high
    python generator/illustrate.py --dry-run    # show prompts, no API calls

Key: OPENAI_API_KEY env var or openai_apikey.txt in the project root.
============================================================"""

import argparse
import base64
import io
import json
import os
import sys
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"

parser = argparse.ArgumentParser(description="Generate gpt-image-1 art for Mr 6 adventures")
parser.add_argument("--only", help="illustrate a single problem id")
parser.add_argument("--force", action="store_true", help="regenerate even if a PNG already exists")
parser.add_argument("--quality", default="medium", choices=["low", "medium", "high"])
parser.add_argument("--dry-run", action="store_true", help="print prompts without calling the API")
parser.add_argument("--workers", type=int, default=3, help="parallel requests (default 3)")
args = parser.parse_args()


def key_from_file(name):
    p = ROOT / name
    if p.exists():
        lines = p.read_text(encoding="utf-8").strip().splitlines()
        if lines:
            return lines[0].strip() or None
    return None


OPENAI_KEY = os.environ.get("OPENAI_API_KEY") or key_from_file("openai_apikey.txt")
if not OPENAI_KEY and not args.dry_run:
    sys.exit("[fail] No OpenAI key found — set OPENAI_API_KEY or create openai_apikey.txt.")

CHARACTER_SHEET = """Mr 6 is NOT a human — he is a living, heroic NUMBER SIX. His body
is a big, bold, clearly readable numeral "6" about as tall as a person: smooth, rounded,
glossy golden-bronze, shaped exactly like the digit 6. Exactly two eyes sit SIDE BY SIDE high on
the numeral's upper stem, well above the loop — never inside the loop, and never more
than two eyes; the loop of the 6 stays plain and empty like a belly. His eyes are
steely, narrowed and intelligent — half-lidded with small sharp pupils and strong
expressive eyebrows, one eyebrow arched in a wry, knowing, confident look, like a
razor-sharp wit sizing up his opponent. NEVER wide, round, vacant, surprised or goofy
cartoon eyes. He has NO nose and NO beak — only eyes, eyebrows, and at most a subtle
confident mouth line on the smooth golden numeral. Thin sturdy arms and legs extend from the numeral's
body, with brown adventurer gloves and boots. His knightly gear: a small silver knight
helmet with a rose-pink plume perched on top of the 6, a flowing deep-blue cape on his
back, and a silver sword in one hand. Friendly, brave, confident hero posture. The digit-6
silhouette must stay clearly readable, and this exact character design must be identical
in every image."""

STYLE_SHEET = """Style: elegant medieval anime storybook illustration — painterly
cel-shaded fantasy anime in the spirit of classic theatrical fantasy anime films,
warm magical lighting, rich colors, dramatic but friendly composition, appealing to
children and adults alike. Absolutely no gore, no frightening realism, no text or
letters in the image (the number 6 on the shield is the only glyph allowed)."""

# Hand-written scene direction for the starter pack. Problems generated by the
# Story Forge carry their own imagePrompt field; anything without either falls
# back to its story text.
SCENES = {
    "potion-of-six-strengths":
        "In a moonlit enchanted forest, Mr 6 gathers glowing red berries, blue mushrooms and "
        "silver leaves into a bubbling green cauldron while a huge but goofy iron-skinned ogre "
        "lumbers between distant trees.",
    "sleeping-giants-snores":
        "A colossal gentle giant sleeps across a starlit valley like a range of hills, snoring "
        "big Zzz clouds, while tiny Mr 6 tiptoes toward a tunnel beneath him under a full moon.",
    "bridge-trolls-toll":
        "At golden sunset, a big grumpy but comical troll blocks an old stone bridge over a "
        "river while Mr 6 counts silver coins from three little pouches, a castle on the far hill.",
    "gloomwings-fireflies":
        "In a pitch-dark magical forest, Mr 6 holds up a glass jar glowing with golden fireflies, "
        "lighting a lost puppy nearby, while a giant velvety shadow bat with purple eyes looms in the "
        "treetops.",
    "sneakfingers-pies":
        "On moonlit village rooftops, a sneaky hooded thief dashes away clutching a berry pie, "
        "dripping a trail of berries, while Mr 6 points up at him from the cobblestone street below "
        "beside a warm bakery window full of pies.",
    "screechias-egg-heist":
        "On a dramatic sunset cliff, Mr 6 climbs toward nests full of pearly dragon eggs while a "
        "flamboyant feathered harpy shrieks and circles overhead.",
    "duplicatus-of-the-deep":
        "A gigantic teal sea serpent rises from moonlit ocean waves, towering over a small fishing "
        "boat where Mr 6 stands bravely at the prow with sword raised.",
    "hydrania-hundred-headed":
        "In a misty green swamp, a many-headed hydra with eight snaky necks glares down at Mr 6, "
        "who calmly offers up a wheel of cheese instead of his sword.",
    "wizard-halflings-curse":
        "At purple dusk, Mr 6 gallops on horseback toward a dark wizard tower while behind him a "
        "gentle stone giant shrinks amid swirling violet curse sparkles.",
    "gobblegrims-gold":
        "Inside a torch-lit cave, a scrawny goblin king with a crooked crown perches atop a huge "
        "glittering mountain of gold coins as Mr 6 strides in with sword drawn.",
    "skeleton-legion":
        "In a green-torch-lit crypt, neat rows of comical rattling skeleton soldiers march toward "
        "Mr 6, who braces behind his glowing golden shield with the number 6.",
    "mirror-witch-multiplia":
        "In a grand hall of ornate mirrors under moonlight, a cackling witch splits into fading "
        "copies of herself while Mr 6 polishes his shield into a mirror to show her reflection.",
    "duskwings-lantern":
        "On a starless black crag, Mr 6 holds a blazing golden lantern high, revealing a huge "
        "shadow dragon half-dissolving into the darkness at the edge of the light.",
    "grimtides-flood":
        "In a storm, Mr 6 rows a small boat through rising waves toward a lighthouse where three "
        "children wait on a high ledge, while giant teal sea-monster tentacles rise from the water.",
    "grimscales-armor":
        "Before a volcanic backdrop, an armored wyvern covered in black iron plates rears up as Mr 6 "
        "strikes with his glowing sword, golden sparks flying off the armor.",
    "torchfire-wolves":
        "On dark moonless hills near a sheep pen, Mr 6 raises a bright torch as a circle of shadow "
        "wolves with amber eyes dissolves into wisps at the edge of the firelight.",
    "blackmaws-treasure":
        "At warm sunset on a cliff road above a village, Mr 6 stands proudly beside three open "
        "treasure chests overflowing with gold while a big defeated bandit sits glumly nearby.",
    "frostfang-ice-wyrm":
        "A long serpentine ice wyrm winds down from glacier peaks toward a snowy valley of villages, "
        "half frozen and half warmly lit, as Mr 6 rides hard on horseback through the snow.",
}


def compress_to_webp(png_bytes, max_width=1280, quality=80):
    """Shrink API PNGs (~2.4 MB) to phone-friendly WebP (~150-250 KB)."""
    from PIL import Image
    im = Image.open(io.BytesIO(png_bytes)).convert("RGB")
    if im.width > max_width:
        im.thumbnail((max_width, max_width * 4))
    out = io.BytesIO()
    im.save(out, format="WEBP", quality=quality, method=6)
    return out.getvalue()


def build_prompt(problem):
    scene = SCENES.get(problem["id"]) or problem.get("imagePrompt") or (
        f"Mr 6 bravely faces {problem['monster']}. {problem['story']}"
    )
    return (f"{CHARACTER_SHEET}\nScene: {scene}\n"
            f"The monster looks impressive but storybook-friendly, not scary.\n{STYLE_SHEET}")


def generate_image(prompt, retries=3):
    last_err = None
    for attempt in range(1, retries + 1):
        req = urllib.request.Request(
            "https://api.openai.com/v1/images/generations",
            data=json.dumps({
                "model": "gpt-image-1",
                "prompt": prompt,
                "size": "1536x1024",
                "quality": args.quality,
                "n": 1,
            }).encode("utf-8"),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {OPENAI_KEY}",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=600) as res:
                data = json.loads(res.read().decode("utf-8"))
            b64 = (data.get("data") or [{}])[0].get("b64_json")
            if not b64:
                raise RuntimeError("API returned no image data")
            return compress_to_webp(base64.b64decode(b64))
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", errors="replace")[:300]
            last_err = RuntimeError(f"HTTP {e.code}: {body}")
            if e.code in (429, 500, 502, 503) and attempt < retries:
                time.sleep(10 * attempt)
                continue
            raise last_err from None
        except Exception as e:
            last_err = e
            if attempt < retries:
                time.sleep(5 * attempt)
                continue
            raise
    raise last_err


def illustrate(rel):
    path = CONTENT / rel
    problem = json.loads(path.read_text(encoding="utf-8"))
    pid = problem["id"]

    has_webp = (CONTENT / "images" / f"{pid}.webp").exists()
    if not args.force and (has_webp and problem.get("image", "").endswith(".webp")):
        return (pid, "skipped (already has WebP)")
    if args.only and pid != args.only:
        return (pid, None)

    prompt = build_prompt(problem)
    if args.dry_run:
        return (pid, f"DRY RUN prompt:\n{prompt}\n")

    webp = generate_image(prompt)
    image_rel = f"images/{pid}.webp"
    (CONTENT / image_rel).write_bytes(webp)
    problem["image"] = image_rel
    path.write_text(json.dumps(problem, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return (pid, f"OK -> {image_rel} ({len(webp) // 1024} KB)")


def main():
    manifest = json.loads((CONTENT / "manifest.json").read_text(encoding="utf-8"))
    rels = manifest["problems"]
    if args.only:
        rels = [r for r in rels if Path(r).stem == args.only]
        if not rels:
            sys.exit(f"[fail] No problem with id '{args.only}'")

    print(f"[illustrator] {len(rels)} problem(s) to consider - quality: {args.quality}"
          f"{' - DRY RUN' if args.dry_run else ''}")
    done = failed = skipped = 0

    with ThreadPoolExecutor(max_workers=max(1, args.workers)) as pool:
        futures = {pool.submit(illustrate, rel): rel for rel in rels}
        for fut in as_completed(futures):
            rel = futures[fut]
            try:
                pid, msg = fut.result()
                if msg is None:
                    continue
                if msg.startswith("skipped"):
                    skipped += 1
                else:
                    done += 1
                print(f"  [{pid}] {msg}", flush=True)
            except Exception as err:
                failed += 1
                print(f"  [{Path(rel).stem}] FAILED: {err}", flush=True)

    print(f"\n[done] {done} illustrated, {skipped} skipped, {failed} failed.")
    if failed:
        print("[hint] Re-run the same command — finished images are kept, only missing ones retry.")


if __name__ == "__main__":
    main()
